Refactor build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -105,8 +105,9 @@ jobs:
     needs: tap-syntax
     outputs:
       syntax-only: ${{ steps.check-labels.outputs.syntax-only }}
-      runners: ${{ steps.check-labels.outputs.runners }}
+      linux-runner: ${{ steps.check-labels.outputs.linux-runner }}
       fail-fast: ${{ steps.check-labels.outputs.fail-fast }}
+      test-dependents: ${{ steps.check-labels.outputs.test-dependents }}
       timeout-minutes: ${{ steps.check-labels.outputs.timeout-minutes }}
       container: ${{ steps.check-labels.outputs.container }}
       test-bot-formulae-args: ${{ steps.check-labels.outputs.test-bot-formulae-args }}
@@ -139,13 +140,23 @@ jobs:
     if: github.event_name == 'pull_request' && !contains(github.event.head_commit.message, 'skip-build')
     strategy:
       matrix:
-        runner: ${{fromJson(needs.set-environment.outputs.runners)}}
+        include:
+          - runner: 'macos-12-arm64'
+          - runner: 'macos-11-arm64'
+          - runner: 'macos-12'
+          - runner: 'macos-11'
+          - runner: ${{needs.set-environment.outputs.linux-runner}}
+            container: ${{fromJson(needs.set-environment.outputs.container)}}
+            workdir: /github/home
+            timeout: 4320
       fail-fast: ${{fromJson(needs.set-environment.outputs.fail-fast)}}
     runs-on: ${{matrix.runner}}
-    timeout-minutes: ${{fromJson(needs.set-environment.outputs.timeout-minutes)}}
+    container: ${{matrix.container}}
+    timeout-minutes: ${{ matrix.timeout || fromJson(needs.set-environment.outputs.timeout-minutes) }}
     defaults:
       run:
         shell: /bin/bash -e {0}
+        working-directory: ${{matrix.workdir || github.workspace}}
     env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
@@ -154,31 +165,12 @@ jobs:
         if: runner.os == 'macOS'
         run: echo 'PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' >> $GITHUB_ENV
 
-      - name: Set up Linux Homebrew Docker container
+      - name: Prepare Container
         if: runner.os == 'Linux'
-        env:
-          BREW_PATH: /home/linuxbrew/.linuxbrew/Homebrew
-          TAP_PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/shivammathur/homebrew-extensions
         run: |
-          docker run \
-            --detach \
-            --user linuxbrew \
-            --name ${{github.sha}} \
-            --env-file <(env | egrep 'HOMEBREW|GITHUB') \
-            --workdir /tmp/bottles \
-            --pull always \
-            ${{needs.set-environment.outputs.container}} \
-            sleep inf
-          # Fix working directory permissions
-          docker exec --user linuxbrew ${{github.sha}} brew tap shivammathur/homebrew-extensions
-          docker exec --user root ${{github.sha}} chmod 777 /tmp/bottles
-          docker exec --workdir "$BREW_PATH" ${{github.sha}} git pull origin master
-          docker exec --user linuxbrew ${{github.sha}} brew update
-          docker exec --workdir "$TAP_PATH" ${{github.sha}} git remote set-url origin ${{github.event.repository.html_url}}
-          docker exec --workdir "$TAP_PATH" ${{github.sha}} git fetch origin ${{github.sha}} '+refs/heads/*:refs/remotes/origin/*'
-          docker exec --workdir "$TAP_PATH" ${{github.sha}} git remote set-head origin --auto
-          docker exec --workdir "$TAP_PATH" ${{github.sha}} git checkout --force -B master FETCH_HEAD
-
+          sudo chmod 777 ${{matrix.workdir || github.workspace}}
+          sudo useradd _www
+          brew update
       - name: Set up Homebrew
         id: set-up-homebrew
         uses: Homebrew/actions/setup-homebrew@master
@@ -188,94 +180,56 @@ jobs:
         run: |
           latest_stable_xcode_path="$(find -E /Applications -maxdepth 1 -regex '.*Xcode_13.[0-9]+.app' | sort -V | tail -1)"
           sudo xcode-select -s "$latest_stable_xcode_path" || exit 1
+      - run: brew test-bot --only-cleanup-before
 
-      - name: brew test-bot --only-cleanup-before
-        if: runner.os == 'macOS'
-        run: brew test-bot --only-cleanup-before
-
-      - name: Run brew test-bot --only-setup
-        run: |
-          if [ "$RUNNER_OS" = 'macOS' ]; then
-            brew test-bot --only-setup
-          else
-            docker exec ${{github.sha}} brew test-bot --only-setup
-          fi
+      - run: brew test-bot --only-setup
 
       - name: Run brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
         id: brew-test-bot-formulae
         run: |
-          if [ "$RUNNER_OS" = 'macOS' ]; then
-            mkdir bottles
-            cd bottles
-            brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
-          else
-            docker exec ${{github.sha}} brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
-          fi
-
-      - name: Copy results from container
-        if: always() && runner.os == 'Linux'
-        run: docker cp ${{github.sha}}:/tmp/bottles .
-
+          mkdir bottles
+          cd bottles
+          brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
       - name: Failures summary for brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
         if: always()
         run: |
           touch bottles/steps_output.txt
           cat bottles/steps_output.txt
           rm bottles/steps_output.txt
-
-      - name: Run brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
-        run: |
-          if [ "$RUNNER_OS" = 'macOS' ]; then
-            cd bottles
-            brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
-          else
-            docker exec ${{github.sha}} brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
-          fi
-
-      - name: Copy results from container
-        if: always() && runner.os == 'Linux'
-        run: docker cp ${{github.sha}}:/tmp/bottles .
-
-      - name: Failures summary for brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
+      - name: Output brew linkage result
         if: always()
         run: |
-          touch bottles/steps_output.txt
-          cat bottles/steps_output.txt
-          rm bottles/steps_output.txt
-
+          cat bottles/linkage_output.txt
+          rm bottles/linkage_output.txt
       - name: Output brew bottle result
         if: always()
         run: |
           cat bottles/bottle_output.txt
           rm bottles/bottle_output.txt
-
+      - name: Run brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
+        if: ${{(success() || failure()) && fromJson(needs.set-environment.outputs.test-dependents)}}
+        run: |
+          cd bottles
+          brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
+      - name: Failures summary for brew test-bot ${{ needs.set-environment.outputs.test-bot-dependents-args }} --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}
+        if: ${{always() && fromJson(needs.set-environment.outputs.test-dependents) == true}}
+        run: |
+          touch bottles/steps_output.txt
+          cat bottles/steps_output.txt
+          rm bottles/steps_output.txt
       - name: Upload logs
-        if: failure()
+        if: always()
         uses: actions/upload-artifact@main
         with:
           if-no-files-found: ignore
           name: logs-${{ matrix.runner }}
-          path: bottles/logs
+          path: ${{matrix.workdir || github.workspace}}/bottles/logs
 
       - name: Delete logs and home
         if: always()
         run: |
           rm -rvf bottles/logs
           rm -rvf bottles/home
-
-      - name: Fix bottles json
-        run: |
-          cd bottles
-          if [ "$RUNNER_OS" = 'macOS' ]; then
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i '' s~homebrew/bottles-extensions~${{ github.repository_owner }}/extensions~ {} +
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i '' s~bottles-extensions~extensions~ {} +
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i '' s~bottles~extensions~ {} +
-          else
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i s~homebrew/bottles-extensions~${{ github.repository_owner }}/extensions~ {} +
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i s~bottles-extensions~extensions~ {} +
-            LC_ALL=C find . -type f -name '*.json' -exec sed -i s~bottles~extensions~ {} +
-          fi
-
       - name: Count bottles
         id: bottles
         if: always()
@@ -283,17 +237,16 @@ jobs:
           cd bottles
           count=$(ls *.json | wc -l | xargs echo -n)
           echo "$count bottles"
-          echo "count=$count" >> "$GITHUB_OUTPUT"
+          echo "count=$count" | sudo tee -a "$GITHUB_OUTPUT"
           failures=$(ls failed/*.json | wc -l | xargs echo -n)
           echo "$failures failed bottles"
-          echo "failures=$failures" >> "$GITHUB_OUTPUT"
-
+          echo "failures=$failures" | sudo tee -a "$GITHUB_OUTPUT"
       - name: Upload failed bottles
         if: always() && steps.bottles.outputs.failures > 0
         uses: actions/upload-artifact@main
         with:
           name: bottles-${{ matrix.runner }}
-          path: bottles/failed
+          path: ${{matrix.workdir || github.workspace}}/bottles/failed
 
       # Must be run before the `Upload bottles` step so that failed
       # bottles are not included in the `bottles` artifact.
@@ -306,16 +259,12 @@ jobs:
         uses: actions/upload-artifact@main
         with:
           name: bottles
-          path: bottles
+          path: ${{matrix.workdir || github.workspace}}/bottles
 
       - name: Post cleanup
         if: always()
         run: |
-          if [ "$RUNNER_OS" = 'Linux' ]; then
-            docker rm -f ${{github.sha}}
-          else
-            brew test-bot --only-cleanup-after
-          fi
+          brew test-bot --only-cleanup-after
           rm -rvf bottles
           if [ -L "$GITHUB_WORKSPACE" ]; then
             sudo rm -rf "$GITHUB_WORKSPACE"
